name: build
on:
  push:
    branches:
    - master
    paths-ignore:
    - 'docker/**'
    - 'docs/**'
    - 'notebooks/**'
    - '.github/markdown.yml'
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
    - master
    paths-ignore:
    - 'docker/**'
    - 'docs/**'
    - 'notebooks/**'
    - '.github/markdown.yml'

jobs:
  universal:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    if: ${{ github.event_name == 'push' || github.event.pull_request.draft == false }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        node_version: ['12', '14']
        os: [ubuntu-latest, macOS-latest]
    steps:
    - name: cancel previous runs
      uses: imgcook/cancel-workflow-action@81524cf
      with:
        access_token: ${{ github.token }}
        exception: master
    - uses: actions/checkout@v2
    - name: restore lerna
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          */*/node_modules
          packages/boa/pybind11
          packages/boa/pyodide
        key: ${{ runner.os }}-${{ matrix.node_version }}-${{ hashFiles('**/package-lock.json,packages/boa/pybind11/Makefile,packages/boa/pyodide/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.node_version }}
          ${{ runner.os }}
    - name: restore miniconda
      uses: actions/cache@v2
      with:
        path: |
          packages/boa/.miniconda
          packages/boa/Miniconda3-latest*.sh
          packages/boa/.CONDA_INSTALL_DIR
        key: ${{ runner.os }}-miniconda-${{ hashFiles('packages/boa/Miniconda3-latest*.sh') }}
        restore-keys: |
          ${{ runner.os }}-miniconda
    - name: Using Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: Building Pipcook
      run: |
        yarn
        yarn build
        yarn init-dev
        du -h -d 1
    - name: daemon start
      run: |
        ./packages/cli/dist/bin/pipcook daemon start
    - name: install plugins from specific pipeline
      run: |
        python3 --version
        python --version
        which python
        echo $PATH
        ./packages/cli/dist/bin/pipcook pipeline install ./example/pipelines/chinese-poem-creation.json
        ./packages/cli/dist/bin/pipcook pipeline install https://raw.githubusercontent.com/alibaba/pipcook/master/example/pipelines/text-bayes-classification.json
