name: pipeline
on:
  pull_request:
    branches:
    - master
  # schedule:
  # - cron: "0 2 * * *"

jobs:
  universal:
    name: Run ${{ matrix.pipeline }} on node ${{ matrix.node_version }}
    runs-on: [self-hosted, linux, gpu]
    strategy:
      matrix:
        node_version: ['12']
        pipeline: ['mnist-image-classification', 'databinding-image-classification', 'text-bayes-classification', 'fasttext']
    steps:
    - uses: actions/checkout@v2
    - name: Using Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: install
      run: npm install
    - name: compile
      run: npm run build
    - name: initilize pipcook
      run: |
        ./packages/cli/dist/bin/pipcook daemon start
    - name: pipeline
      run: npm run test:pipeline -- ${{ matrix.pipeline }}
