name: pipeline
on:
  schedule:
  - cron: "0 2 * * *"

jobs:
  universal:
    name: Run ${{ matrix.pipeline }} on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['12']
        os: [ubuntu-latest]
        pipeline: ['mnist-image-classification', 'databinding-image-classification-resnet', 'text-bayes-classification', 'fasttext']
    steps:
    - uses: actions/checkout@v2
    - name: Using Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: install
      run: npm install
    - name: compile
      run: npm run build
    - name: initilize pipcook
      env:
        NODE_ENV: local
      run: |
        ./packages/cli/dist/bin/pipcook init
        ./packages/cli/dist/bin/pipcook daemon start
    - name: pipeline
      run: npm run test:pipeline -- ${{ matrix.pipeline }}
    - name: wasm export pipeline
      run: |
        git clone https://github.com/emscripten-core/emsdk.git && cd emsdk
        ./emsdk install latest && source ./emsdk_env.sh
        ./packages/cli/dist/bin/pipcook daemon stop
        export WASM=1 && ./packages/cli/dist/bin/pipcook run ./example/pipelines/databinding-image-classification-mobilenet.json
